<?php
 $routes = array(
    '/dRaczekProjekt/' => array('controller' => 'HomeController', 'action' => 'index', 'path' => 'MVC/controllers/user/home/'),
    '/dRaczekProjekt/home' => array('controller' => 'HomeController', 'action' => 'index', 'path' => 'MVC/controllers/user/home/'),
    '/dRaczekProjekt/login' => array('controller' => 'LoginUserController', 'action' => 'displayLoginPage', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/register' => array('controller' => 'RegisterUserController', 'action' => 'displayRegisterPage', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/register/sendForm' => array('controller' => 'RegisterUserController', 'action' => 'registrationProcess', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/register/verify/:token' => array('controller' => 'RegisterUserController', 'action' => 'registrationVerify', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/login/sendForm' => array('controller' => 'LoginUserController', 'action' => 'loginProcess', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/logout' => array('controller' => 'LogoutUserController', 'action' => 'logout', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/resetPassword/stepOne' => array('controller' => 'StepOnePasswordResetController', 'action' => 'displayStepOnePasswordReset', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/resetPassword/stepOne/send' => array('controller' => 'StepOnePasswordResetController', 'action' => 'stepOnePasswordReset', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/resetPassword/stepTwo/token/:token' => array('controller' => 'StepTwoPasswordResetController', 'action' => 'displayStepTwoPasswordReset', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/resetPassword/stepTwo/send' => array('controller' => 'StepTwoPasswordResetController', 'action' => 'stepTwoPasswordReset', 'path' => 'MVC/controllers/user/auth/'),
    '/dRaczekProjekt/user' => array('controller' => 'UserDetailsController', 'action' => 'displayUserDetailsPage', 'path' => 'MVC/controllers/user/userPanel/'),
    '/dRaczekProjekt/user/edit' => array('controller' => 'EditUserDetailsController', 'action' => 'displayEditUserDetailsPage', 'path' => 'MVC/controllers/user/userPanel/'),
    '/dRaczekProjekt/user/edit/send' => array('controller' => 'EditUserDetailsController', 'action' => 'editUserDetailsPage', 'path' => 'MVC/controllers/user/userPanel/'),
    '/dRaczekProjekt/user/changePassword' => array('controller' => 'ChangeUserPasswordController', 'action' => 'displayChangeUserPasswordPage', 'path' => 'MVC/controllers/user/userPanel/'),
    '/dRaczekProjekt/user/changePassword/send' => array('controller' => 'ChangeUserPasswordController', 'action' => 'changeUserPassword', 'path' => 'MVC/controllers/user/userPanel/'),
    '/dRaczekProjekt/admin/login' => array('controller' => 'LoginAdminController', 'action' => 'displayLoginAdminPage', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/login/send' => array('controller' => 'LoginAdminController', 'action' => 'loginAdmin', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/home' => array('controller' => 'AdminPanelController', 'action' => 'displayAdminHomePage', 'path' => 'MVC/controllers/admin/panel/'),
    '/dRaczekProjekt/admin/manage/users' => array('controller' => 'ManageUsersController', 'action' => 'displayManageUsersPage', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/manage/users:pageableUsers' => array('controller' => 'ManageUsersController', 'action' => 'displayManageUsersPage', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/manage/users/suspend/:id' => array('controller' => 'ManageUsersStateController', 'action' => 'suspendUser', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/manage/users/activate/:id' => array('controller' => 'ManageUsersStateController', 'action' => 'activateUser', 'path' => 'MVC/controllers/admin/user/'),
    '/dRaczekProjekt/admin/manage/categories' => array('controller' => 'ManageCategoriesController', 'action' => 'displayManageCategoriesPage', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories:pageableCategories' => array('controller' => 'ManageCategoriesController', 'action' => 'displayManageCategoriesPage', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/suspend/:id' => array('controller' => 'ManageCategoryStateController', 'action' => 'suspendCategory', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/activate/:id' => array('controller' => 'ManageCategoryStateController', 'action' => 'activateCategory', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/add' => array('controller' => 'AddCategoryController', 'action' => 'displayAddCategoryPage', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/add/send' => array('controller' => 'AddCategoryController', 'action' => 'addCategory', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/delete/:id' => array('controller' => 'ManageCategoryStateController', 'action' => 'deleteCategory', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/edit/form/:id' => array('controller' => 'EditCategoryController', 'action' => 'displayEditCategoryPage', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/categories/edit/send' => array('controller' => 'EditCategoryController', 'action' => 'editCategory', 'path' => 'MVC/controllers/admin/categories/'),
    '/dRaczekProjekt/admin/manage/products' => array('controller' => 'ManageProductsController', 'action' => 'displayManageProductsPage', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products:pageableProducts' => array('controller' => 'ManageProductsController', 'action' => 'displayManageProductsPage', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/suspend/:id' => array('controller' => 'ManageProductStateController', 'action' => 'suspendProduct', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/activate/:id' => array('controller' => 'ManageProductStateController', 'action' => 'activateProduct', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/delete/:id' => array('controller' => 'ManageProductStateController', 'action' => 'deleteProduct', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/edit/form/:id' => array('controller' => 'EditProductController', 'action' => 'displayEditProductPage', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/edit/form/send' => array('controller' => 'EditProductController', 'action' => 'editProduct', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/add' => array('controller' => 'AddProductController', 'action' => 'displayAddProductPage', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/admin/manage/products/add/send' => array('controller' => 'AddProductController', 'action' => 'addProduct', 'path' => 'MVC/controllers/admin/products/'),
    '/dRaczekProjekt/products/:id' => array('controller' => 'DisplayProductViewController', 'action' => 'displayProductView', 'path' => 'MVC/controllers/products/'),
    '/dRaczekProjekt/cart/add/:id' => array('controller' => 'AddToCartController', 'action' => 'add', 'path' => 'MVC/controllers/cart/'),
    '/dRaczekProjekt/cart' => array('controller' => 'DisplayCartViewController', 'action' => 'displayCartView', 'path' => 'MVC/controllers/cart/'),
    '/dRaczekProjekt/cart/delete/:id' => array('controller' => 'DeleteFromCartController', 'action' => 'delete', 'path' => 'MVC/controllers/cart/'),
    '/dRaczekProjekt/cart/update' => array('controller' => 'UpdateCartValueController', 'action' => 'update', 'path' => 'MVC/controllers/cart/'),
    
);
?>